import groovy.transform.Field

@Field String POM_VERSION = ''
@Field String TARGET_REPO = ''
@Field String GHCR_CREDENTIALS = 'ghcr-credentials'
@Field String SERVICE_NAME = 'capit-schedule'
@Field String KUBE_CREDENTIALS = 'kubeconfig-dev'

pipeline {
	agent any
    tools {
		jfrog 'jfrog-cli-latest'
    }
    stages {
		stage('Checkout') {
			steps {
				checkout([
                    $class: 'GitSCM',
                    branches: [[name: "*/dev"]],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [
                        [$class: 'PathRestriction',
                            includedRegions: '${SERVICE_NAME}/.*'
                        ]
                    ],
                    submoduleCfg: [],
                    userRemoteConfigs: [[url: 'https://github.com/Gill-Sans/ci-api.git']]
                ])
            }
        }

        stage('Determine Version') {
			steps {
				script {
					POM_VERSION = sh(
						script: """
					  		cd ${SERVICE_NAME}
					  		mvn -B -Dstyle.color=never help:evaluate \
						  		-Dexpression=project.version -q -DforceStdout \
							| sed -r 's/\\x1B\\[[0-9;]*[mK]//g'
						""",
						returnStdout: true
				  	).trim()

				  	echo "POM version: ${POM_VERSION}"

				  	if (POM_VERSION.contains('SNAPSHOT')) {
						TARGET_REPO = 'libs-snapshot-local'
				  	} else {
						TARGET_REPO = 'libs-release-local'
				  	}
				  echo "Deploying to ${TARGET_REPO}"
				}
		  	}
		}

        stage('run unit tests') {
			steps {
				sh "cd ${SERVICE_NAME} && mvn test -B --settings ~/.m2/settings.xml"
			}
		}

        stage('Build') {
			steps {
				sh "cd ${SERVICE_NAME} && mvn clean install -B -DskipTests --settings ~/.m2/settings.xml"
            }
        }

        stage('Upload Artifact') {
			steps {
				jf "rt u ${SERVICE_NAME}/target/*.jar ${TARGET_REPO} --build-name=${SERVICE_NAME} --build-number=${BUILD_NUMBER}"
            }
        }

        stage('Build Container Image') {
			steps {
				script {
					sh """
						cd ${SERVICE_NAME}
						podman build --format docker -t ghcr.io/gill-sans/ci-api/${SERVICE_NAME}:${POM_VERSION} .
					  """
        		}
      		}
		}

		stage('Publish Container Image') {
			steps {
				withCredentials([usernamePassword(
				  credentialsId: GHCR_CREDENTIALS,
				  usernameVariable: 'GHCR_USER',
				  passwordVariable: 'GHCR_TOKEN'
				)]) {
					sh """
					echo "${GHCR_TOKEN}" | podman login ghcr.io --username="${GHCR_USER}" --password-stdin

					podman push ghcr.io/gill-sans/ci-api/${SERVICE_NAME}:${POM_VERSION}

					podman tag ghcr.io/gill-sans/ci-api/${SERVICE_NAME}:${POM_VERSION} ghcr.io/gill-sans/ci-api/${SERVICE_NAME}:latest
					podman push ghcr.io/gill-sans/ci-api/${SERVICE_NAME}:latest
					"""
				}
			}
		}

		stage('Deploy to Kubernetes cluster') {
			steps {
				withCredentials([file(
				  credentialsId: KUBE_CREDENTIALS,
				  variable: 'KUBECONFIG'
				)]) {
					sh """
					echo "Applying manifest to dev cluster…"
					kubectl --kubeconfig=${KUBECONFIG} apply -f K8s-config-dev.yaml

					echo "Waiting for rollout of deployment/${SERVICE_NAME}…"
					kubectl --kubeconfig=${KUBECONFIG} rollout status deployment/${SERVICE_NAME} --timeout=300s
					"""
				}
			}
		}
    }
    post {
		success {
			echo "Build & Deploy succeeded for ${SERVICE_NAME}!"
        }
        failure {
			echo "Build & Deploy failed. Check the logs for issues."
        }
    }
}