version: "3.8"

services:
  postgres:
    image: docker.io/library/postgres:17.4
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./podman/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - capit

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=https://capit-dev.keycloak.mertenshome.com
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY=edge
      - KC_PROXY_HEADERS=xforwarded
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=password
    command:
      - start
      - --http-enabled=true
      - --http-port=8080
      - --import-realm
      - --proxy=edge
      - --hostname-strict=false
    ports:
      - "8180:8080"
    volumes:
      - ./podman/keycloak/realms:/opt/keycloak/data/import
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - capit

  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:7.6.5
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    networks:
      - capit

  kafka:
    image: docker.io/confluentinc/cp-kafka:7.6.5
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://192.168.0.53:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - capit

  kafka-ui:
    image: docker.io/provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9095:8080"
    environment:
      # Define a single cluster pointing at your 'kafka' service
      KAFKA_CLUSTERS_0_NAME: capit-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - capit

  axonserver:
    image: docker.io/axoniq/axonserver:2024.2.4
    container_name: axonserver
    volumes:
      - axonserver-data:/axonserver/data
      - axonserver-events:/axonserver/events
      - axonserver-log:/axonserver/log
    secrets:
      - source: axonserver-properties
        target: /axonserver/config/axonserver.properties
    environment:
      - AXONIQ_AXONSERVER_STANDALONE=TRUE
    ports:
      - "8024:8024"
      - "8124:8124"
    networks:
      - capit

volumes:
  postgres_data:
  axonserver-data:
  axonserver-events:
  axonserver-log:

networks:
  capit:

secrets:
  axonserver-properties:
    file: ./podman/axonserver/config/axonserver.properties
