version: "3.8"

services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: >
      bash -c "docker-entrypoint.sh postgres &
      sleep 10;
      psql -v ON_ERROR_STOP=1 --username=postgres --dbname=postgres -c \"CREATE DATABASE keycloak;\" 2>/dev/null || true;
      psql -v ON_ERROR_STOP=1 --username=postgres --dbname=postgres -c \"CREATE DATABASE schedules;\" 2>/dev/null || true;
      psql -v ON_ERROR_STOP=1 --username=postgres --dbname=postgres -c \"CREATE DATABASE interactions;\" 2>/dev/null || true;
      wait"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    environment:
      - KC_HTTP_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB_VENDOR=postgres
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=password
    command: ["start-dev", "--import-realm"]
    ports:
      - "8180:8080"
    volumes:
      - ./podman/keycloak/realms:/opt/keycloak/data/import
    depends_on:
      - postgres
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.5
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.5
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"

  axonserver:
    image: axoniq/axonserver:2024.2.4
    container_name: axonserver
    volumes:
      - axonserver-data:/axonserver/data
      - axonserver-events:/axonserver/events
      - axonserver-log:/axonserver/log
    secrets:
      - source: axonserver-properties
        target: /axonserver/config/axonserver.properties
    environment:
      - 'AXONIQ_AXONSERVER_STANDALONE=TRUE'
    ports:
      - "8024:8024"
      - "8124:8124"
    networks:
      - axon

volumes:
  postgres_data:
  axonserver-data:
  axonserver-events:
  axonserver-log:

networks:
  axon:

secrets:
  axonserver-properties:
    file: ./podman/axonserver/config/axonserver.properties