import groovy.transform.Field

@Field String POM_VERSION = ''
@Field String TARGET_REPO = ''

pipeline {
	agent any
    tools {
		jfrog 'jfrog-cli-latest'
    }
    stages {
		stage('Checkout') {
			steps {
				checkout([
                    $class: 'GitSCM',
                    branches: [[name: "*/dev"]],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [
                        [$class: 'PathRestriction',
                            includedRegions: 'capit-common/.*'
                        ]
                    ],
                    submoduleCfg: [],
                    userRemoteConfigs: [[url: 'https://github.com/Gill-Sans/ci-api.git']]
                ])
            }
        }

        stage('Determine Version') {
			steps {
				script {
					POM_VERSION = sh(
						script: """
					  		cd capit-common
					  		mvn -B -Dstyle.color=never help:evaluate \
						  		-Dexpression=project.version -q -DforceStdout \
							| sed -r 's/\\x1B\\[[0-9;]*[mK]//g'
						""",
						returnStdout: true
				  	).trim()

				  	echo "POM version: ${POM_VERSION}"

				  	if (POM_VERSION.contains('SNAPSHOT')) {
						TARGET_REPO = 'libs-snapshot-local'
				  	} else {
						TARGET_REPO = 'libs-release-local'
				  	}
				  echo "Deploying to ${TARGET_REPO}"
				}
		  	}
		}

        stage('run unit tests') {
			steps {
				sh "cd capit-common && mvn test -B --settings ~/.m2/settings.xml"
			}
		}

        stage('Build') {
			steps {
				sh "cd capit-common && mvn clean install -B -DskipTests --settings ~/.m2/settings.xml"
            }
        }

        stage('Upload Artifact') {
			steps {
				jf "rt u capit-common/target/*.jar ${TARGET_REPO} --build-name=capit-common --build-number=${BUILD_NUMBER}"
            }
        }
    }

    post {
		success {
			echo "Build & Deploy succeeded for capit-common!"
        }
        failure {
			echo "Build & Deploy failed. Check the logs for issues."
        }
    }
}