import groovy.transform.Field

@Field String POM_VERSION = ''
@Field String TARGET_REPO = ''
@Field String GHCR_CREDENTIALS = 'ghcr-credentials'

pipeline {
	agent any
    tools {
		jfrog 'jfrog-cli-latest'
    }
    stages {
		stage('Checkout') {
			steps {
				checkout([
                    $class: 'GitSCM',
                    branches: [[name: "*/dev"]],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [
                        [$class: 'PathRestriction',
                            includedRegions: 'capit-gateway/.*'
                        ]
                    ],
                    submoduleCfg: [],
                    userRemoteConfigs: [[url: 'https://github.com/Gill-Sans/ci-api.git']]
                ])
            }
        }

        stage('Determine Version') {
			steps {
				script {
					POM_VERSION = sh(
						script: """
					  		cd capit-gateway
					  		mvn -B -Dstyle.color=never help:evaluate \
						  		-Dexpression=project.version -q -DforceStdout \
							| sed -r 's/\\x1B\\[[0-9;]*[mK]//g'
						""",
						returnStdout: true
				  	).trim()

				  	echo "POM version: ${POM_VERSION}"

				  	if (POM_VERSION.contains('SNAPSHOT')) {
						TARGET_REPO = 'libs-snapshot-local'
				  	} else {
						TARGET_REPO = 'libs-release-local'
				  	}
				  echo "Deploying to ${TARGET_REPO}"
				}
		  	}
		}

        stage('run unit tests') {
			steps {
				sh "cd capit-gateway && mvn test -B --settings ~/.m2/settings.xml"
			}
		}

        stage('Build') {
			steps {
				sh "cd capit-gateway && mvn clean install -B -DskipTests --settings ~/.m2/settings.xml"
            }
        }

        stage('Upload Artifact') {
			steps {
				jf "rt u capit-gateway/target/*.jar ${TARGET_REPO} --build-name=capit-gateway --build-number=${BUILD_NUMBER}"
            }
        }

        stage('Build Container Image') {
			steps {
				script {
					  sh """
						cd capit-gateway
						podman build --format docker -t ghcr.io/gill-sans/ci-api/capit-gateway:${POM_VERSION} .
					  """
        		}
      		}
		}

		stage('Publish Container Image') {
			steps {
				withCredentials([usernamePassword(
				  credentialsId: GHCR_CREDENTIALS,
				  usernameVariable: 'GHCR_USER',
				  passwordVariable: 'GHCR_TOKEN'
				)]) {
					sh """
					echo "${GHCR_TOKEN}" | podman login ghcr.io --username="${GHCR_USER}" --password-stdin

					podman push ghcr.io/gill-sans/ci-api/capit-gateway:${POM_VERSION}

					podman tag ghcr.io/gill-sans/ci-api/capit-gateway:${POM_VERSION} ghcr.io/gill-sans/ci-api/capit-gateway:latest
					podman push ghcr.io/gill-sans/ci-api/capit-gateway:latest
					"""
				}
			}
		}

		stage('Deploy to Kubernetes') {
			steps {
				withCredentials([file(
				  credentialsId: 'kubeconfig-dev',
				  variable: 'KUBECONFIG'
				)]) {
					sh """
					echo "Applying manifest to dev cluster..."
					kubectl --kubeconfig=$KUBECONFIG apply -f k8s-config-local.yaml --record

					echo "Waiting for rollout..."
					kubectl --kubeconfig=$KUBECONFIG rollout status deployment/${JOB_NAME} --timeout=120s
				  	"""
				}
		  	}
		}
    }

    post {
		success {
			echo "Build & Deploy succeeded for capit-gateway!"
        }
        failure {
			echo "Build & Deploy failed. Check the logs for issues."
        }
    }
}