spring:
    application:
        name: capit-users
    datasource:
        url: jdbc:postgresql://localhost:5432/users
        username: postgres
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
server:
    port: 8080
