spring:
  application:
    name: capit-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://capit-dev.keycloak.mertenshome.com/realms/capit
server:
  port: 9001
