spring:
  application:
    name: capit-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/Capit
server:
  port: 9001

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
