spring:
  application:
    name: capit-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/Capit
server:
  port: 9001

logging:
    level:
        org.springframework.security: TRACE
        org.springframework.security.oauth2: TRACE

