interactions:
  topic:
    checkin:
      name: checkin-events
      partitions: 3
      replicas: 1
spring:
  application:
    name: capit-interactions
  datasource:
    url: jdbc:postgresql://192.168.0.53:5432/interactions
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: 192.168.0.53:29092
    consumer:
      properties:
        spring.json.use.type.headers: true
        spring.json.value.default.type: com.capit.events.UserEvent
      group-id: capit-interactions
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081



