spring:
  application:
    name: capit-interactions
  datasource:
    url: jdbc:postgresql://localhost:5432/interactions
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: capit-interactions
server:
  port: 8081




