interactions:
  topic:
    checkin:
      name: checkin-events
      partitions: 3
      replicas: 1
spring:
  application:
    name: capit-interactions
  datasource:
    url: jdbc:postgresql://localhost:5432/interactions
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: capit-interactions
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8081

logging:
  level:
    org.springframework.web.socket: TRACE
    org.springframework.web.reactive.socket: TRACE
    org.springframework.web.reactive.handler: TRACE



