spring:
  application:
    name: capit-schedule
  datasource:
    url: jdbc:postgresql://192.168.0.53:5432/schedules
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8082



