spring:
  application:
    name: capit-schedule
  datasource:
    url: jdbc:postgresql://localhost:5432/schedules
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
logging:
  level:
    org.springframework.web.socket: TRACE